apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:latest
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      ports:
        - containerPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
